mainSections = ["post", "about"]

[footer]
since = 2023

[sidebar]
compact = false
doctor = "BlueSpace"
level = 112
subtitle = "CSer in ICT <br /> Research Direction:<br /> OS, Cloud, Virtualization<br />Hobbies: Game, Music, Movies<br />Tech, Photograph, Travel"

  [sidebar.avatar]
  enabled = true
  local = true
  src = "img/avatar.jpeg"
